Update c-cpp.yml

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -13,11 +13,22 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
-    - name: configure
-      run: chmod +x snakegame.cpp && ./snakegame.cpp
-    - name: make
-      run: make
-    - name: make check
-      run: make check
-    - name: make distcheck
-      run: make distcheck
+    - name: Build and Run C Program
+      run: |
+        gcc snakegame.c -o snakegame_c -lncurses
+        if [ $? -eq 0 ]; then
+          ./snakegame_c
+        else
+          echo "C Compilation failed. Exiting."
+          exit 1
+        fi
+
+    - name: Build and Run C++ Program
+      run: |
+        g++ snakegame.cpp -o snakegame_cpp -lncurses
+        if [ $? -eq 0 ]; then
+          ./snakegame_cpp
+        else
+          echo "C++ Compilation failed. Exiting."
+          exit 1
+        fi
